# Generated by Django 3.0 on 2020-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hstaff',
            name='degree',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BAMS', 'BAMS'), ('BUMS', 'BUMS'), ('BHMS', 'BHMS'), ('BYNS', 'BYNS'), ('BPT', 'BPT'), ('BMLT', 'BMLT'), ('BOT', 'BOT'), ('D.Pharm.', 'D.Pharm.'), ('B.Pharm.', 'B.Pharm.'), ('BOT', 'BOT'), ('MD', 'MD'), ('MS', 'MS'), ('DNB', 'DNB')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hstaff',
            name='specialization',
            field=models.CharField(default='', max_length=150),
        ),
    ]
