# Generated by Django 3.0 on 2020-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHWebApp', '0002_auto_20200426_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hstaff',
            name='degree',
            field=models.CharField(choices=[('', 'Select Degree *'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BAMS', 'BAMS'), ('BUMS', 'BUMS'), ('BHMS', 'BHMS'), ('BYNS', 'BYNS'), ('BPT', 'BPT'), ('BMLT', 'BMLT'), ('BOT', 'BOT'), ('D.Pharm.', 'D.Pharm.'), ('B.Pharm.', 'B.Pharm.'), ('BOT', 'BOT'), ('MD', 'MD'), ('MS', 'MS'), ('DNB', 'DNB')], default='', max_length=150),
        ),
    ]
