# Generated by Django 3.0 on 2020-04-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHWebApp', '0004_auto_20200426_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hstaff',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='hstaff',
            name='password',
        ),
        migrations.AddField(
            model_name='hstaff',
            name='profession',
            field=models.CharField(choices=[('AD', 'Admin'), ('AC', 'Accountant'), ('DC', 'Doctor'), ('CS', 'Clerical Staff'), ('RC', 'Receptionist'), ('JS', 'Janitorial Staff'), ('LT', 'Lab Technician'), ('NR', 'Nurse'), ('PS', 'Physcian'), ('HK', 'House Keeping')], default='DC', max_length=150),
        ),
    ]
