# Generated by Django 3.0 on 2020-05-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHWebApp', '0006_auto_20200429_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='registeredDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hstaff',
            name='registeredDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
