# Generated by Django 3.0 on 2020-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHWebApp', '0007_auto_20200506_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contry',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='fname',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hregno',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='lname',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='city',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='contry',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='degree',
            field=models.CharField(choices=[('', 'Select Degree *'), ('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('DNB', 'DNB'), ('BDS', 'BDS'), ('BAMS', 'BAMS'), ('BUMS', 'BUMS'), ('BHMS', 'BHMS'), ('BYNS', 'BYNS'), ('BPT', 'BPT'), ('BMLT', 'BMLT'), ('BOT', 'BOT'), ('D.Pharm.', 'D.Pharm.'), ('B.Pharm.', 'B.Pharm.'), ('BOT', 'BOT')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='district',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='email',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='fname',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='lname',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='profession',
            field=models.CharField(choices=[('AD', 'Admin'), ('AC', 'Accountant'), ('DC', 'Doctor'), ('CS', 'Clerical Staff'), ('RC', 'Receptionist'), ('JS', 'Janitorial Staff'), ('LT', 'Lab Technician'), ('NR', 'Nurse'), ('PS', 'Physcian'), ('HK', 'House Keeping')], default='AD', max_length=2),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='specialization',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='hstaff',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
