# Generated by Django 3.0 on 2020-05-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHWebApp', '0008_auto_20200506_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='password',
        ),
    ]
