# Generated by Django 3.0 on 2020-05-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DHWebApp', '0009_remove_hospital_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('adharid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=35)),
                ('lname', models.CharField(max_length=35)),
                ('birthdate', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=8)),
                ('bloodgrp', models.CharField(choices=[('', 'Select Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=5)),
                ('email', models.CharField(default='', max_length=75)),
                ('phone', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('zipcode', models.CharField(max_length=6)),
                ('registeredDate', models.DateTimeField()),
                ('visitcount', models.IntegerField(default=0)),
                ('hregno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHWebApp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedDoctor', models.CharField(max_length=120)),
                ('meet', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('adharid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMSystem.Patient')),
                ('hregno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHWebApp.Hospital')),
            ],
        ),
    ]
